### ISSUE TITLE
Issue with authelia

### ISSUE THREAD

**Issue by imtiazalijamil** [JamesTurland/JimsGarage#1]
Hi I use the same config but getting an error with authelia. can you please advise how to to fix

`time="2023-08-15T00:15:51+01:00" level=error msg="Configuration: authentication_backend: you must ensure either the 'file' or 'ldap' authentication backend is configured"
authelia    | time="2023-08-15T00:15:51+01:00" level=error msg="Configuration: access control: 'default_policy' option 'deny' is invalid: when no rules are specified it must be 'two_factor' or 'one_factor'"
authelia    | time="2023-08-15T00:15:51+01:00" level=error msg="Configuration: storage: configuration for a 'local', 'mysql' or 'postgres' database must be provided"
authelia    | time="2023-08-15T00:15:51+01:00" level=error msg="Configuration: storage: option 'encryption_key' is required"
authelia    | time="2023-08-15T00:15:51+01:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured"
authelia    | time="2023-08-15T00:15:51+01:00" level=fatal msg="Can't continue due to the errors loading the configuration"`

**Comment by JamesTurland** [comment]
Hi, you need to set the config file up properly, it looks like you are just using the default one which isn't set. Please rewatch the video as it tells you all of the items to configure.
