### ISSUE TITLE
Kubernetes/Traefik-PiHole/Manifest/PiHole/PiHole-Deployment.yaml file has superfluous and erroneous containerports for cloudflared

### ISSUE THREAD

**Issue by rvanderwouw** [JamesTurland/JimsGarage#115]
Kubernetes/Traefik-PiHole/Manifest/PiHole/PiHole-Deployment.yaml has this section for cloudflared:

      containers:
      - image: visibilityspots/cloudflared
        imagePullPolicy: IfNotPresent
        name: cloudflared
        ports:
        - containerPort: 53
          name: dns
          protocol: TCP
        - containerPort: 67
          name: dns-udp
          protocol: UDP

Two comments with this:
dns-udp is not port 67 but 53 afaik. 67 is DHCP.
But more: these containerports are not needed because the pihole container is accessing port 5054 internally only.

Also, unrelated: the cloudflared environment specifies a TUNNEL_METRICS port of 3000 on localhost, which is also non existent within the pods when running. 

Suggestion: remove the ports section and the tunnel_metrics environment variable.

**Comment by JamesTurland** [comment]
Thanks, that's tested and resolved.
