### ISSUE TITLE
K3sup script fail requiring a password.

### ISSUE THREAD

**Issue by Sivivatu** [JamesTurland/JimsGarage#19]
I am testing the install script but using unraid as the hypervisor rather than proxmox. AFAIK this should make a difference, it just changes the creation of the base vms.

The issue I'm seeing is:

```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```

This is returned when the install part of the script runs (ie # Step 1: Bootstrap First k3s Node). Looking at the issue [here](https://github.com/alexellis/k3sup/issues/298) it appears that sudo is a requirement for K3sup. this would mean the script shouldn't work, but it obviously does. what am I missing?

**Comment by JamesTurland** [comment]
Are you using certificate based authentication for SSH or standard passwords? You should use certificates for this script (AKA keys).

**Comment by kasdk3** [comment]
cloud-init on Proxmox sets ssh NOPASSWD in `/etc/sudoers.d/`.

- on Unraid create a new file in `/etc/sudoers.d/` (90-cloud-init-users)
- add `YOURUSERNAME ALL=(ALL) NOPASSWD:ALL`
- set permissions `chmod 0444 90-cloud-init-users`


WARNING doing this will disable the sudo password for the user.

**Comment by Sivivatu** [comment]
That makes sense. I'm not running on proxmox so didn't use the cloud-init process. Will try this
