### ISSUE TITLE
K3s failing to switch back to master

### ISSUE THREAD

**Issue by aliencord** [JamesTurland/JimsGarage#27]
One node (K3s-02) tends to go offline temporarily and K3s-01 picks up for it (shows in rancher). Then doesn't comeback online, after restarting the project completely still having issues.

**Comment by JamesTurland** [comment]
What resources do you have on your MN? Same subnet etc?

**Comment by aliencord** [comment]
Yes same subnet, hardware wise 8gb of memory, 8 cores, 32gb of storage. (And yes each node was cloned correctly)
Ip reservations go as follows
- rm-vm  10.1.40.49
- VIP    10.1.40.50
- K3s-01 10.1.40.51
- K3s-02 10.1.40.52
- K3s-03 10.1.40.53
- k3s-04 10.1.40.54
- K3s-05 10.1.40.55
