### ISSUE TITLE
Traefik + PiHole Script not working RKE2

### ISSUE THREAD

**Issue by AmadorSV** [JamesTurland/JimsGarage#28]
I'm trying to run the script script on my wsl ubuntu distro. the deploy command is creating the helm and manifest forlder but there is nothing inside of it.

Before running the script
![image](https://github.com/JamesTurland/JimsGarage/assets/9062027/d86f2bf3-d0cd-4785-93a2-29ddc0140265)

After runnning the script
![image](https://github.com/JamesTurland/JimsGarage/assets/9062027/45e19859-92d1-4bda-808d-75ea65bd8fc9)

Terminal output:
`personal@AMADOR-PC:~$ ./deploy.sh
     __  _          _        ___
     \ \(_)_ __ ___( )__    / _ \__ _ _ __ __ _  __ _  ___
      \ \ | '_ ` _ \/ __|  / /_\/ _` | '__/ _` |/ _` |/ _ \
   /\_/ / | | | | | \__ \ / /_\  (_| | | | (_| | (_| |  __/
   \___/|_|_| |_| |_|___/ \____/\__,_|_|  \__,_|\__, |\___|
                                                |___/
              Traefik, Cert-Manager, and PiHole

              https://youtube.com/@jims-garage

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
unzip is already the newest version (6.0-26ubuntu3.1).
The following packages were automatically installed and are no longer required:
  ieee-data python3-argcomplete python3-distutils python3-dnspython python3-lib2to3 python3-libcloud python3-lockfile
  python3-netaddr python3-pycryptodome python3-requests-toolbelt python3-selinux python3-simplejson
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1411k    0 1411k    0     0  1260k      0 --:--:--  0:00:01 --:--:-- 1260k
Archive:  master.zip
d57cbaafb4c93beb088f2cf75556a58ec09bf271
   creating: /home/personal/jimsgarage/JimsGarage-main/
  inflating: /home/personal/jimsgarage/JimsGarage-main/.pre-commit-config.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Authelia/
   creating: /home/personal/jimsgarage/JimsGarage-main/Authelia/Authelia/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Authelia/Authelia/configuration.yml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Authelia/Authelia/docker-compose.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Authelia/Authelia/users_database.yml
   creating: /home/personal/jimsgarage/JimsGarage-main/Authelia/Nginx/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Authelia/Nginx/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Authelia/Traefik/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Authelia/Traefik/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Authentik/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Authentik/.env
   creating: /home/personal/jimsgarage/JimsGarage-main/Authentik/Web-Proxies/
    linking: /home/personal/jimsgarage/JimsGarage-main/Authentik/Web-Proxies/.env  -> ../.env
  inflating: /home/personal/jimsgarage/JimsGarage-main/Authentik/Web-Proxies/authentik-docker-compose.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Authentik/Web-Proxies/example-nginx-docker-compose.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Authentik/Web-Proxies/traefik-conf.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Authentik/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Cloudflare-Tunnel/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Cloudflare-Tunnel/docker-compose.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Cloudflare-Tunnel/macvlan
   creating: /home/personal/jimsgarage/JimsGarage-main/Code-Server/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Code-Server/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Crowdsec/
   creating: /home/personal/jimsgarage/JimsGarage-main/Crowdsec/Traefik/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Crowdsec/Traefik/config.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Crowdsec/Traefik/traefik.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Crowdsec/acquis.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Crowdsec/docker-compose.yml
   creating: /home/personal/jimsgarage/JimsGarage-main/Frigate/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Frigate/config.yml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Frigate/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/GPU_passthrough/
  inflating: /home/personal/jimsgarage/JimsGarage-main/GPU_passthrough/readme.md
   creating: /home/personal/jimsgarage/JimsGarage-main/Gotify/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Gotify/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Grafana-Monitoring/
   creating: /home/personal/jimsgarage/JimsGarage-main/Grafana-Monitoring/Part-2/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Grafana-Monitoring/Part-2/mibs.txt
  inflating: /home/personal/jimsgarage/JimsGarage-main/Grafana-Monitoring/Part-2/prometheus.yml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Grafana-Monitoring/Part-2/telegraf.conf
  inflating: /home/personal/jimsgarage/JimsGarage-main/Grafana-Monitoring/docker-compose.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Grafana-Monitoring/prometheus.yml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Grafana-Monitoring/telegraf.conf
   creating: /home/personal/jimsgarage/JimsGarage-main/Headscale/
   creating: /home/personal/jimsgarage/JimsGarage-main/Headscale/Tailscale-Client/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Headscale/Tailscale-Client/docker-compose,yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Headscale/config.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Headscale/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Headscale/with-Traefik/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Headscale/with-Traefik/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Homelab-Buyer's-Guide/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Homelab-Buyer's-Guide/Q3-2023.md
   creating: /home/personal/jimsgarage/JimsGarage-main/Homepage/
   creating: /home/personal/jimsgarage/JimsGarage-main/Homepage/Homepage/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Homepage/Homepage/docker-compose.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Homepage/Homepage/services.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Immich/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Immich/.env
  inflating: /home/personal/jimsgarage/JimsGarage-main/Immich/docker-compose.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Immich/hwaccel.yml
   creating: /home/personal/jimsgarage/JimsGarage-main/Jellyfin/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Jellyfin/docker-compose.yml
   creating: /home/personal/jimsgarage/JimsGarage-main/Jitsi/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Jitsi/.env
  inflating: /home/personal/jimsgarage/JimsGarage-main/Jitsi/docker-compose.yml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Jitsi/gen-passwords.sh
   creating: /home/personal/jimsgarage/JimsGarage-main/Keycloak/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Keycloak/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Cloud-Init/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Cloud-Init/readme.md
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Create-manifest-helm/
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Create-manifest-helm/Portainer/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Create-manifest-helm/Portainer/default-headers.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Create-manifest-helm/Portainer/ingress.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Create-manifest-helm/Portainer/values.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Create-manifest-helm/WireGuard-Easy/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Create-manifest-helm/WireGuard-Easy/default-headers.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Create-manifest-helm/WireGuard-Easy/deployment.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Create-manifest-helm/WireGuard-Easy/ingress.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Create-manifest-helm/WireGuard-Easy/ingressRouteUDP.yaml
 extracting: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Create-manifest-helm/readme.md
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Docker-Kubernetes-Data-Migration/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Docker-Kubernetes-Data-Migration/readme.md
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/GitOps/
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/GitOps/Gotify/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/GitOps/Gotify/default-headers.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/GitOps/Gotify/deployment.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/GitOps/Gotify/ingress.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/GitOps/Grafana/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/GitOps/Grafana/fleet.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/GitOps/Grafana/values.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/GitOps/readme.md
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/K3S-Deploy/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/K3S-Deploy/k3s.sh
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/K3S-Deploy/readme.md
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Longhorn/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Longhorn/longhorn-K3S.sh
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Longhorn/longhorn-RKE2.sh
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Longhorn/longhorn.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Longhorn/readme.md
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/RKE2/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/RKE2/k3s
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/RKE2/rke2.sh
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Rancher-Deployment/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Rancher-Deployment/readme.md
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/Cert-Manager/
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/Cert-Manager/Certificates/   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/Cert-Manager/Certificates/Production/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/Cert-Manager/Certificates/Production/jimsgarage-production.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/Cert-Manager/Issuers/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/Cert-Manager/Issuers/letsencrypt-production.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/Cert-Manager/Issuers/secret-cf-token.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/Cert-Manager/values.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/Dashboard/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/Dashboard/ingress.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/Dashboard/middleware.yaml

  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/Dashboard/secret-dashboard.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/default-headers.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Helm/Traefik/values.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Manifest/
   creating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Manifest/PiHole/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Manifest/PiHole/PiHole-Deployment.yaml

  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Manifest/PiHole/default-headers.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/Manifest/PiHole/ingress.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/deploy.sh
  inflating: /home/personal/jimsgarage/JimsGarage-main/Kubernetes/Traefik-PiHole/readme.md
   creating: /home/personal/jimsgarage/JimsGarage-main/Logo/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Logo/Jim's Garage-1 (1).mp4
  inflating: /home/personal/jimsgarage/JimsGarage-main/Logo/Jim's Garage-1 (1).png
  inflating: /home/personal/jimsgarage/JimsGarage-main/Logo/Jim's Garage-1 (2).png
  inflating: /home/personal/jimsgarage/JimsGarage-main/Logo/Jim's Garage-1 (3).png
  inflating: /home/personal/jimsgarage/JimsGarage-main/Logo/Jim's Garage-1 (4).png
  inflating: /home/personal/jimsgarage/JimsGarage-main/Logo/Jim's Garage-1 (5).png
  inflating: /home/personal/jimsgarage/JimsGarage-main/Logo/Jim's Garage-1.mp4
  inflating: /home/personal/jimsgarage/JimsGarage-main/Logo/Jim's Garage-1.png
  inflating: /home/personal/jimsgarage/JimsGarage-main/Logo/Jim'sGarage-1(2).png
   creating: /home/personal/jimsgarage/JimsGarage-main/Nextcloud/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Nextcloud/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Pihole/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Pihole/docker-compose.yml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Pihole/ubuntu port 53 fix
   creating: /home/personal/jimsgarage/JimsGarage-main/Portainer/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Portainer/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Proxmox-Backup-Server/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Proxmox-Backup-Server/readme.md
  inflating: /home/personal/jimsgarage/JimsGarage-main/README.md
   creating: /home/personal/jimsgarage/JimsGarage-main/Synapse/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Synapse/docker-compose.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Synapse/homeserver.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Synapse/mautrix-discord-bridge/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Synapse/mautrix-discord-bridge/docker-compose.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Synapse/mautrix-discord-bridge/example-config.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Synapse/mautrix-discord-bridge/example-registration.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Synapse/readme.md
   creating: /home/personal/jimsgarage/JimsGarage-main/Torrent-VPN/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Torrent-VPN/docker-compose.yml
   creating: /home/personal/jimsgarage/JimsGarage-main/Traefik-Secure/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Traefik-Secure/config.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Traefik-Secure/docker-compose.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Traefik-Secure/traefik.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Traefik/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Traefik/docker-compose.yml
   creating: /home/personal/jimsgarage/JimsGarage-main/Traefik/traefik-config/
 extracting: /home/personal/jimsgarage/JimsGarage-main/Traefik/traefik-config/acme.json
 extracting: /home/personal/jimsgarage/JimsGarage-main/Traefik/traefik-config/config.yml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Traefik/traefik-config/traefik.yml
   creating: /home/personal/jimsgarage/JimsGarage-main/Trilium/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Trilium/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/UptimeKuma/
  inflating: /home/personal/jimsgarage/JimsGarage-main/UptimeKuma/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Vaultwarden/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Vaultwarden/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Web-Servers/
   creating: /home/personal/jimsgarage/JimsGarage-main/Web-Servers/Hugo/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Web-Servers/Hugo/docker-compose.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Web-Servers/Hugo/site-build-command
   creating: /home/personal/jimsgarage/JimsGarage-main/Web-Servers/Nginx/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Web-Servers/Nginx/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Web-Servers/WordPress/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Web-Servers/WordPress/.env
  inflating: /home/personal/jimsgarage/JimsGarage-main/Web-Servers/WordPress/docker-compose.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/Wireguard/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Wireguard/docker-compose.yml
   creating: /home/personal/jimsgarage/JimsGarage-main/Zitadel/
  inflating: /home/personal/jimsgarage/JimsGarage-main/Zitadel/docker-compose.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Zitadel/example-zitadel-config.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Zitadel/example-zitadel-init-steps.yaml
  inflating: /home/personal/jimsgarage/JimsGarage-main/Zitadel/example-zitadel-secrets.yaml
   creating: /home/personal/jimsgarage/JimsGarage-main/rClone/
  inflating: /home/personal/jimsgarage/JimsGarage-main/rClone/docker-compose.yml
   creating: /home/personal/jimsgarage/JimsGarage-main/rClone/mount/
  inflating: /home/personal/jimsgarage/JimsGarage-main/rClone/mount/docker-compose.yml
  inflating: /home/personal/jimsgarage/JimsGarage-main/rClone/mount/windows_mount.bat
  inflating: /home/personal/jimsgarage/JimsGarage-main/rClone/remote-upload
  inflating: /home/personal/jimsgarage/JimsGarage-main/rClone/sync_script
   creating: /home/personal/jimsgarage/JimsGarage-main/restic/
  inflating: /home/personal/jimsgarage/JimsGarage-main/restic/docker-compose.yml
finishing deferred symbolic links:
  /home/personal/jimsgarage/JimsGarage-main/Authentik/Web-Proxies/.env -> ../.env
cp: cannot stat '/home/personal/jimsgarage/Traefik-tlsmain/Kubernetes/Traefik-PiHole/*': No such file or directory`

**Comment by AmadorSV** [comment]
To fix that I edited the files on my local machine and copied them to where they're supposed to be but I'm getting two errors:

![image](https://github.com/JamesTurland/JimsGarage/assets/9062027/abcb3039-1c15-4f35-a1cf-4d0373d65271)
error: the path "/home/personal/Helm/Traefik/Cert-Manager/Certificates/Production/traefik-tlsproduction.yaml" does not exist
error: error: error parsing /home/personal/Manifest/PiHole/PiHole-Deployment.yaml: error converting YAML to JSON: yaml: line 39: did not find expected whitespace or line break

**Comment by AmadorSV** [comment]
I Fixed the error, seems like I was using a password with symbols and that was causing the error

``

**Comment by JamesTurland** [comment]
Great, thanks for letting me know.
