### ISSUE TITLE
k3s deploy error nginx address not working

### ISSUE THREAD

**Issue by ksullivan86** [JamesTurland/JimsGarage#83]
I am getting an error during the deployment of the script:

Error from server (InternalError): error when creating "/home/ubuntu/ipAddressPool.yaml": Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": no endpoints available for service "webhook-service"

I am assuming my problems have to do with this error, if I got to the nginx address I get no connection. I tried a lil bit of problem solving with my limited knowledge and found the data in the screen shots but I am not sure how to fix these problems.
![Screenshot (209)](https://github.com/JamesTurland/JimsGarage/assets/34048885/e9cbcb54-72a6-4c12-ab6a-57973b846766)
![Screenshot (210)](https://github.com/JamesTurland/JimsGarage/assets/34048885/9378fce0-e3b6-4bda-b6a7-196dcc0c34be)
![Screenshot (211)](https://github.com/JamesTurland/JimsGarage/assets/34048885/631432bd-1c77-4a84-8111-07716c5ff0f8)
![Screenshot (212)](https://github.com/JamesTurland/JimsGarage/assets/34048885/f454744d-0f44-4983-902b-ae61dc5f42eb)

**Comment by jelleriecker** [comment]
For what it's worth: This seems to be a bit intermitted . I've just ran the k3s.sh three times on 3 sets (3m, 3w) of brand new vm's (ub-24.04) as an experiment to see if it works. and 1 of the 3 deployments was giving me an external IP.

**Comment by jelleriecker** [comment]
Well I'll be damned. just ran the script for the second time on the same set of vm's out of curiousity and now i'm getting a external ip.

Not sure if fix or workaround.

**Comment by ksullivan86** [comment]
I made a new template using the non minimal 23.10 and it installed no problem, I think I used the minimal image last time and I am guessing that was the problem
